version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}
      RPC_URL: ${RPC_URL_TRANSFER}
      TARGET_TRANSFER_ADDRESS: ${TARGET_TRANSFER_ADDRESS}
      TARGET_DONATION_ADDRESS: ${TARGET_DONATION_ADDRESS}
      START_BLOCK: ${START_BLOCK}
    ports:
      - "8000:8000"
    restart: always
    command: ["./app"]

volumes:
  db_data:
